<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Autogestor.Domain/Autogestor.Domain.csproj" />
    <ProjectReference Include="../../src/Autogestor.Application/Autogestor.Application.csproj" />
    <ProjectReference Include="../../src/Autogestor.Contract/Autogestor.Contract.csproj" />
  </ItemGroup>

</Project>