<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Autogestor.Contract/Autogestor.Contract.csproj" />
  </ItemGroup>

</Project>
